<div class="container-default">
    <div class="bg-section-02">
        <div class="flex ha-end pr-2">
            <a href="<?= $block->getAddUrl()?>" class="variant-yellow a-btn px-3"><i class="a-icon a-btn__icon material-icons">add</i><?= __('build') ?></a>
        </div>
        <div class="flex flex-cols-3 g-2 py-4">
            <div class="">
                <button class="w-100 a-btn a-btn--small variant-yellow"><?= __('all') ?></button>
            </div>
            <div class="">
                <button class="w-100 a-btn a-btn--small variant-white"><?= __('inprocess') ?></button>
            </div>
            <div class="">
                <button class="w-100 a-btn a-btn--small variant-white"><?= __('expire') ?></button>
            </div>
        </div>
        <div class="flex flex-cols-1 flex-cols-sm-2 g-2">
           <?php $coupons = $block->getListCoupons()->getItems(); ?>
           <?php foreach ($coupons as $coupon):?>
            <div>
                <div class="h-100 bg-section-02">
                    <h3 class="text-bold">
                        <?= $coupon->getName(); ?>
                    </h3>
                    <p class="my-2"><?= $coupon->getFromDate() . " - " . $coupon->getToDate() ?></p>
                    <p class="text-blue">฿<?= $coupon->getDiscountAmount();  ?>% discount</p>
                    <p class="h3 text-right p-3"><?= $coupon->getCode();?></p>
                    <div class="flex ha-end va-center g-2">
                        <div>
                            <a href="<?= $block->getEditUrl($coupon->getRuleId())?>" class="">
                                <button class="variant-yellow a-btn a-btn--small">
                                    <span class="a-btn__text">correct</span>
                                </button>
                            </a>
                        </div>
                        <div>
                            <a href="<?= $block->getDeleteUrl($coupon->getRuleId())?>">
                                <button href="" class="a-btn a-btn--small">
                                   <span class="a-btn__text">Delete</span>
                                </button>
                            </a>
                            
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach ?>
        </div>
    </div>
</div>
