<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

//Load product by product id
$scopeConfig = $objectManager->create('\Magento\Framework\App\Config\ScopeConfigInterface');
$configHelper = $objectManager->create('\Wiki\VendorsConfig\Helper\Data');
$vendorSession = $objectManager->create('\Wiki\Vendors\Model\Session');
$scopeConfig = $configHelper->getVendorConfig(
    'general/store_information/logo',
    $vendorSession->getVendor()->getId()
);
$basePath = 'ves_vendors/logo/';
$path =  $basePath. $scopeConfig;
$imageHelper = $objectManager->create('\Wiki\Vendors\Helper\Image');
$image = $imageHelper->init($scopeConfig, '', [])
        ->setBaseMediaPath($basePath)
        ->backgroundColor([250,250,250])
        ->resize(100, 100);;
$image = $image->getUrl();
if($scopeConfig == null){
    $image = $block->getViewFileUrl('images/user.png');
}
?>
<div class="user-panel">
    <div class="pull-left image">
      <img src="<?php /* @escapeNotVerified */ echo $image?>" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
      <p><?php echo $block->getVendorName();?></p>
      <a href="#"><i class="fa fa-circle text-success"></i> <?php echo __('Online') ?></a>
    </div>
</div>
<div class="divider"></div>