<?php
   $objectManager =  '\Magento\Framework\App\ObjectManager'::getInstance();
   $context = $objectManager->get('Magento\Framework\App\Http\Context');
   $isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
   if($isLoggedIn) {
    $block->test();
 
  $listNoti = $block->getNotificationCollection();
  // print_r($listNoti->getData()); exit;
 
 ?>
<div class="container">

    <section id="cart"> 
      

   
      
<?php


  foreach($listNoti->getData() as $item){
    $mess = $item['message'];
       
    if($item['noti_admin_id'] == 0){

    
?>
 <article class="product">

        <header>
          <a class="remove" href="<?php echo $block->getURLOder($mess); ?>">
            <img src="<?php echo $imgProduct = $block->imgProduct($mess); ?>" alt="">
          </a>
        </header>
        <a href="<?php echo $block->getURLOder($mess); ?>">
        <div class="content">
        
          <h1><?php echo $mess;  ?></h1>

          <?php echo $imgProduct = $block->getContent($mess); ?>

        
        </div>

        </a>
      </article>
      

<?php
  
        // echo $imgProduct = $block->imgProduct($item['message']);
        
        // echo $block->getContent($item['message']);
  } else {
    $listAdmin = $block->getNotiAdmin($item['noti_admin_id']);
     
?>
<article class="product">

<header>
  <a class="remove" href="<?php echo $block->getURLDetailNoti() . $item['noti_admin_id']; ?>">
    <img src="<?php echo $block->getBaseUrl().'pub/media/wiki_notification/images/'.$listAdmin['image']; ?>" alt="">
  </a>
</header>
<a href="<?php echo $block->getURLDetailNoti() . $item['noti_admin_id']; ?>">
<div class="content" style = 'overflow: auto;'>

  <h1><?php echo $listAdmin['title'];  ?></h1>

  <?php echo $listAdmin['summary']; ?>


</div>

</a>
</article>
<?php

  }
}

       
?>
     

    

    

    </section>

  </div>
  <?php } else {
    $redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
    $redirect->setRedirect('customer/account/login');
  } ?>

