<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

use Wiki\VendorsProduct\Block\Dashboard;

/** @var  Dashboard $block */

$totals = $block->getTotals();
?>

<div id="product-dashboard" data-bind="scope: 'dashboard'">
    <div class="container-md">
        <h1 class="mb-5">Manage Product</h1>

        <div class="p-seller-product__search bg-section">
            <div class="a-form">
                <div class="">
                    <div class="a-form-input flex flex-nowrap a-form-input--prepend">
                        <div class="a-form-input__prepend">
                            <i class="a-icon material-icons">search</i>
                        </div>
                        <input type="text" placeholder="Search for auction items in the store.">
                    </div>
                    <div class="a-form__message">

                    </div>
                </div>
            </div>
            <div class="a-form">
                <label class="d-block py-2 pr-4 h4">
                    <?= __('select category') ?>
                </label>
                <div class="">
                    <div
                        class="vue-treeselect vue-treeselect--single vue-treeselect--searchable vue-treeselect--has-value vue-treeselect--open-below">
                        <div class="vue-treeselect__control">
                            <div class="vue-treeselect__value-container">
                                <!--                            <div class="vue-treeselect__single-value"> (unknown)</div>-->
                                <div
                                    class="vue-treeselect__placeholder vue-treeselect-helper-zoom-effect-off vue-treeselect-helper-hide">
                                    Select Category
                                </div>
                                <div class="vue-treeselect__input-container">
                                    <input type="text" autocomplete="off" tabindex="0" class="vue-treeselect__input">
                                </div>
                            </div>
                            <div title="Clear value" class="vue-treeselect__x-container">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 348.333 348.333"
                                     class="vue-treeselect__x">
                                    <path
                                        d="M336.559 68.611L231.016 174.165l105.543 105.549c15.699 15.705 15.699 41.145 0 56.85-7.844 7.844-18.128 11.769-28.407 11.769-10.296 0-20.581-3.919-28.419-11.769L174.167 231.003 68.609 336.563c-7.843 7.844-18.128 11.769-28.416 11.769-10.285 0-20.563-3.919-28.413-11.769-15.699-15.698-15.699-41.139 0-56.85l105.54-105.549L11.774 68.611c-15.699-15.699-15.699-41.145 0-56.844 15.696-15.687 41.127-15.687 56.829 0l105.563 105.554L279.721 11.767c15.705-15.687 41.139-15.687 56.832 0 15.705 15.699 15.705 41.145.006 56.844z"></path>
                                </svg>
                            </div>
                            <div class="vue-treeselect__control-arrow-container">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 292.362 292.362"
                                     class="vue-treeselect__control-arrow">
                                    <path
                                        d="M286.935 69.377c-3.614-3.617-7.898-5.424-12.848-5.424H18.274c-4.952 0-9.233 1.807-12.85 5.424C1.807 72.998 0 77.279 0 82.228c0 4.948 1.807 9.229 5.424 12.847l127.907 127.907c3.621 3.617 7.902 5.428 12.85 5.428s9.233-1.811 12.847-5.428L286.935 95.074c3.613-3.617 5.427-7.898 5.427-12.847 0-4.948-1.814-9.229-5.427-12.85z"></path>
                                </svg>
                            </div>
                        </div>
                        <div class="vue-treeselect__menu-container" style="z-index: 999;">

                        </div>
                    </div>
                </div>
            </div>
            <div class="flex ha-end g-2 pb-3">
                <div class="col-3">
                    <div class="a-form">
                        <div class="">
                            <div class="a-form-input flex flex-nowrap a-form-input--prepend">
                                <div class="a-form-input__prepend">฿</div>
                                <input type="number" placeholder="From">
                            </div>
                            <div class="a-form__message">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-3">
                    <div class="a-form">
                        <div class="">
                            <div class="a-form-input flex flex-nowrap a-form-input--prepend" min="">
                                <div class="a-form-input__prepend">฿</div>
                                <input type="number" placeholder="To">
                            </div>
                            <div class="a-form__message">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex ha-end g-2">
                <div>
                    <button class="variant-yellow a-btn">
                        <span class="a-btn__text">search</span>
                    </button>
                </div>
                <div>
                    <button class="a-btn">
                        <span class="a-btn__text">Clear</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="p-seller-product__list py-5">
            <h2><?= __($totals . ' products in total') ?></h2>
            <div class="flex ha-end g-2">
                <div>
                    <a href="/seller/product/create" class="">
                        <button class="variant-yellow a-btn">
                            <i class="a-icon a-btn__icon material-icons">add</i>
                            <span class="a-btn__text">add product</span>
                        </button>
                    </a>
                </div>
                <div>
                    <div class="a-dropdown a-dropdown--right a-action">
                        <div class="a-dropdown__btn">
                            <button class="variant-white a-btn a-btn--right" data-bind="click: toggleAction">
                                <i class="a-icon a-btn__icon material-icons">expand_more</i>
                                <span class="a-btn__text">More Actions</span>
                            </button>
                        </div>
                        <div class="a-dropdown__content py-3">
                            <div class="a-dropdown__inner p-3">
                                <a href="/" class="router-link-active">
                                    <p class="p-3">Add multiple products</p>
                                </a>
                                <a href="/" class="router-link-active">
                                    <p class="p-3">Fix multiple products</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="py-5">
            <div>
                <div class="m-product-scard bg-section mb-3">
                    <div class="flex ha-between va-center">
                        <div>
                            <div class="a-form-checkbox m-product-scard__status">
                                <input type="checkbox" id="seller-product-2940" class="select_product" value="true"
                                       data-bind="click: changeSelect()">
                                <label for="seller-product-2940" class="flex flex-nowrap va-center">
                                    Status: Enabled - Type: simple
                                </label>
                            </div>
                        </div>
                        <div>
                            <button class="text-blue a-btn a-btn--no-border">
                                <span class="a-btn__text">Delete</span>
                            </button>
                        </div>
                    </div>
                    <hr class="text-gray hr-nomargin">
                    <div class="flex py-3">
                        <div class="col-3">
                            <figure class="a-thumbnail a-thumbnail--width" style="padding-bottom: 100%;">
                                <img
                                    src="http://cmkp.funsecondlife.com/img/310/300/resize/pub/media/catalog/product/n/o/no_7_1feb2021_1200x800_fun_spm_1_jpg.jpg"
                                    alt="">
                            </figure>
                        </div>
                        <div class="m-product-scard__content col-9 pl-4">
                            <h3 class="mb-3">
                                <a href="/test-2-s85.html" class="" target="_blank">test 2</a>
                            </h3>
                            <div class="flex va-center">
                                <div class="m-product__price pr-4">
                                    <p class="h3">
                                        <strong>43</strong>
                                    </p>
                                </div>
                                <p>Treasury 51111</p>
                            </div>
                            <div class="m-product-scard__btn flex-nowidth g-2">
                                <div>
                                    <a href="/seller/product/update/test-2-S85" class="">
                                        <button class="variant-yellow a-btn">
                                            <i class="a-icon a-btn__icon material-icons">edit</i>
                                            <span class="a-btn__text">
                                            correct
                                        </span>
                                        </button>
                                    </a>
                                </div>
                                <div>
                                    <button class="a-btn">
                                        <i class="a-icon a-btn__icon material-icons">visibility_off</i>
                                        <span class="a-btn__text">Hide</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="m-product-scard bg-section mb-3">
                    <div class="flex ha-between va-center">
                        <div>
                            <div class="a-form-checkbox m-product-scard__status">
                                <input type="checkbox" id="seller-product-2941" class="select_product" value="true"
                                       data-bind="click: changeSelect()">
                                <label for="seller-product-2940" class="flex flex-nowrap va-center">
                                    Status: Enabled - Type: simple
                                </label>
                            </div>
                        </div>
                        <div>
                            <button class="text-blue a-btn a-btn--no-border">
                                <span class="a-btn__text">Delete</span>
                            </button>
                        </div>
                    </div>
                    <hr class="text-gray hr-nomargin">
                    <div class="flex py-3">
                        <div class="col-3">
                            <figure class="a-thumbnail a-thumbnail--width" style="padding-bottom: 100%;">
                                <img
                                    src="http://cmkp.funsecondlife.com/img/310/300/resize/pub/media/catalog/product/n/o/no_7_1feb2021_1200x800_fun_spm_1_jpg.jpg"
                                    alt="">
                            </figure>
                        </div>
                        <div class="m-product-scard__content col-9 pl-4">
                            <h3 class="mb-3">
                                <a href="/test-2-s85.html" class="" target="_blank">test 2</a>
                            </h3>
                            <div class="flex va-center">
                                <div class="m-product__price pr-4">
                                    <p class="h3">
                                        <strong>43</strong>
                                    </p>
                                </div>
                                <p>Treasury 51111</p>
                            </div>
                            <div class="m-product-scard__btn flex-nowidth g-2">
                                <div>
                                    <a href="/seller/product/update/test-2-S85" class="">
                                        <button class="variant-yellow a-btn">
                                            <i class="a-icon a-btn__icon material-icons">edit</i>
                                            <span class="a-btn__text">
                                            correct
                                        </span>
                                        </button>
                                    </a>
                                </div>
                                <div>
                                    <button class="a-btn">
                                        <i class="a-icon a-btn__icon material-icons">visibility_off</i>
                                        <span class="a-btn__text">Hide</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="p-seller-product__footer p-3 bg-section " data-bind="css: { 'p-seller-product__footer--open': showSideBar }">
        <div class="flex ha-between ha-md-flex-end va-center">
            <div class="pr-5">
                <div class="a-form-checkbox">
                    <input type="checkbox" id="auction-select-all" value="true" data-bind="click: selectAll()">
                    <label for="auction-select-all" class="flex flex-nowrap va-center">เลือกทั้งหมด</label>
                </div>
            </div>
            <div>
                <button class="variant-yellow a-btn">
                <span class="a-btn__text">
                    Delete <span data-bind="text: '(' + countChecked() + ')'"> </span>
                </span>
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#product-dashboard": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
    echo $block->getJsLayout(); ?>
        }
    }



</script>
