<script type="text/javascript">
require.config({
	"paths": {
		/*Magento 2.2*/
		"Magento_Catalog/js/components/dynamic-rows-tier-price":"Wiki_VendorsProduct/js/components/dynamic-rows-tier-price",
	    /*End magento 2.2*/
		
        "Magento_Catalog/js/components/import-handler": "Wiki_VendorsProduct/js/components/import-handler",
        "Magento_Catalog/js/components/new-category":"Wiki_VendorsProduct/js/components/new-category",
        "Magento_Catalog/js/components/attribute-set-select":"Wiki_VendorsProduct/js/components/attribute-set-select",
        "Magento_Catalog/js/components/dynamic-rows-import-custom-options":"Wiki_VendorsProduct/js/components/dynamic-rows-import-custom-options",
        "Magento_Catalog/component/file-type-field.js":"Wiki_VendorsProduct/component/file-type-field.js",
        "Magento_Catalog/component/select-type-grid.js":"Wiki_VendorsProduct/component/select-type-grid.js",
        "Magento_Catalog/component/static-type-container.js":"Wiki_VendorsProduct/component/static-type-container.js",
        "Magento_Catalog/component/static-type-input.js":"Wiki_VendorsProduct/component/static-type-input.js",
        "Magento_Catalog/component/static-type-select.js":"Wiki_VendorsProduct/component/static-type-select.js",
        "Magento_Catalog/component/text-type-field.js":"Wiki_VendorsProduct/component/text-type-field.js",
        "Magento_Catalog/js/custom-options-type.js":"Wiki_VendorsProduct/js/custom-options-type.js",
        "Magento_CatalogInventory/js/components/use-config-settings":"Wiki_VendorsProduct/js/components/use-config-settings",
        "Magento_CatalogInventory/js/components/qty-validator-changer":"Wiki_VendorsProduct/js/components/qty-validator-changer",
        "Magento_CatalogInventory/js/components/use-config-min-sale-qty":"Wiki_VendorsProduct/js/components/use-config-min-sale-qty",
        "productGallery":"Wiki_VendorsProduct/js/product-gallery",
        "baseImage":"Wiki_VendorsProduct/catalog/base-image-uploader",
        "Magento_Backend/js/media-uploader":"Wiki_VendorsProduct/js/media-uploader",
        "Magento_Variable/variables":"Wiki_VendorsProduct/js/components/variables"
	}
});
</script>
