<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="admin__data-grid-header admin__data-grid-toolbar">
    <form action="<?php echo $block->getUrl('jobs/product/exportorderedcsv')?>" class="form-import row" method="post">
        <div class="form-export row">
            <div class="admin__field-label export-select col-md-12 col-lg-12 col-sm-12 col-xs-12">
                <label for="product_export" class="admin__control-support-text">
                    <?php /* @escapeNotVerified */ echo __('export from:') ?>
                </label>
                <select name="product_export" id="product_export" class="admin__control-select">
                    <option value="http://dev.magento.market/vendors/reports/product/exportOrderedCsv/">CSV</option>
                    <option value="http://dev.magento.market/vendors/reports/product/exportOrderedExcel/">Excel XML</option>
                </select>
            </div>
            <div class="admin__field-label button-export col-md-12 col-lg-12 col-sm-12 col-xs-12">
                <button id="id_button_export" title="export" type="submit" class="btn btn-default task" data-ui-id="widget-button-0">
                    <span>export</span>
                </button>
            </div>
        </div>
    </form>
</div>