<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// http://dev.magento.market/vendors/jobs/product/exportorderedcsv
// @codingStandardsIgnoreFile

?>
<div class="admin__data-grid-header admin__data-grid-toolbar">
    <form action="<?php echo $block->getUrl('jobs/product/importproduct')?>" class="form-import row" method="post" enctype="multipart/form-data">
        <input type="hidden" id="entity" name="entity" value="catalog_product">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
        <div class="admin__field-label import-select col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <label for="product_import" class="admin__control-support-text">
                <?php /* @escapeNotVerified */ echo __('Import from:') ?>
            </label>
            <select name="product_import" id="product_import" class="admin__control-select">
                <option>CSV</option>
                <option>Excel XML</option>
            </select>
        </div>
        <div class="admin__field field field-import_file  required _required with-note col-md-12 col-lg-12 col-sm-12 col-xs-12" data-ui-id="import-form-container-form-fieldset-element-form-field-import-file">
            <label class="label admin__field-label" for="import_file" data-ui-id="import-form-container-form-fieldset-element-file-import-file-label"><span>Select File to Import</span></label>
            <div class="admin__field-control control">
                <input id="import_file" name="import_file" data-ui-id="import-form-container-form-fieldset-element-file-import-file" value="" title="Select File to Import" class="input-file required-entry _required" type="file" aria-required="true">          
            </div>
        </div>
        <div class="admin__field-label button-import col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <button id="id_button_import" title="Import" type="submit" class="btn btn-default task" data-ui-id="widget-button-0">
                <span>Import</span>
            </button>
        </div>
    </form>
</div>
<script type="text/javascript">
    require(["jquery",'mage/url'], function($, url){
        "use strict";
        $(document).on('click','#id_button_import',function(){
            console.log('Sucess');
            jQuery.ajax({
                url: 'vendors/jobs/product/exportorderedcsv',
                type: "POST",
                data: {data:'success'},
                success: function(response){
                    console.log('Sucess');
                }
            });
        });
    });
</script>