<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $footer = $helper->getStoreConfig('mgstheme/general/footer') ?>
<?php if($footer == '' || $footer == 'footer_1' || $footer == 'footer'): ?>
    <div class="footer-container">
        <span id="ember166" class="anchor-wrapper ember-view">
            <div id="ember167" class="back-to-top-container __1aa78 min-height-reached ember-view">
                <div class="back-to-top-btn">
                    <span class="btn btn-secondary btn-block">
                        <span id="ember168" class="fa fa-chevron-up">
                    </span>
                        <span class="visible-sm-block visible-xs-block">
                        Back to top
                        </span>
                    </span>
                </div>
            </div>
        </span>
        <div class="row site-footer-main">
            <hr class="footer-separator visible-lg">
            <div class="footer-wrapper footer-awo-holder">
                <div id="awo-footer-holder-desktop" class="awo-footer-holder">
                    <div class="col-md-6">
                        <div id="awo-talkable-element-desktop" class="awo-footer-element">
                            <div id="tkbl_widget">Want an extra 25% off? 
                                <a class="link" id="tkbl_widget_link" href="/us/en/content/refer-a-friend?icid=ae:footer:refer_a_friend&amp;traffic_source=footer">Refer A Friend</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div id="awo_qualtrics_0" class="awo-footer-element">
                            <div>
                                <div class="QSI_feedback_link_container">
                                    <span class="cms-avenirdemi">Let us know how we're doing. </span>
                                    <span class="QSI_feedback_link">
                                        <u onclick="window.open('https://aeo.co1.qualtrics.com/jfe/form/SV_eh2MAshrrFcWTUp','AEO Feedback','resizable=yes,width=1000,height=778')">Give Feedback</u>.
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-wrapper footer-wapper-column-mobile">
                <div class="footer-column">
                    <ul class="list-unstyled qa-footer-list-left-column footer-heritage-list">
                        <li class="footer-list-item qa-footer-item-gift-cards">
                            <a href="/us/en/x/gift-cards?navdetail=footer%3Ac1%3Ap1" id="ember1055" class="ember-view">              
                                <span class="footer-list-item-title">Gift Cards</span>
                            </a>            
                            <span class="footer-list-item-sub">Give them what they really want.</span>
                        </li>
                        <li class="footer-list-item qa-footer-item-rewards">
                            <a href="/us/en/myaccount/aeoconnected?navdetail=footer%3Ac1%3Ap2" id="ember1056" class="ember-view">              
                                <span class="footer-list-item-title">AEO Connected Rewards</span>
                            </a>            
                            <span class="footer-list-item-sub">Earn free jeans, bras, shipping &amp; more.</span>
                        </li>
                        <li class="footer-list-item qa-footer-item-credit-cards">
                            <a href="/us/en/content/credit?navdetail=footer%3Ac1%3Ap3" id="ember1057" class="ember-view">              
                                <span class="footer-list-item-title">AEO Connected Credit Cards</span>
                            </a>            
                            <span class="footer-list-item-sub">Take 20% off* your first purchase with your new<br> AEO Connected® credit card</span>
                            <div class="footer-list-item-sub">
                                <a rel="noopener noreferrer" target="_blank" href="https://aeoutfitters.syf.com/eSecurity/Login/login.action?clientId=aeoutfitters&amp;accountType=generic&amp;langId=en" id="ember1058" class="footer-link-pay-bill aecc-sign-in-link qa-aecc-sign-in-link ember-view">Pay Bill</a>|
                                <a target="_blank" href="https://apply.syf.com/eapply/eapply.action?clientCode=AE&amp;cHash=1342177401&amp;subActionId=1000&amp;sitecode=caehpb9b1" id="ember1060" class="footer-link-apply-now aecc-sign-up-link qa-aecc-sign-up-link ember-view">Apply Now</a>
                            </div>
                        </li>
                        <li class="footer-list-item qa-footer-item-mobile-app">
                            <a href="/us/en/x/mobile-app" class="xm-link-to qa-xm-link-to ">
                                <span class="footer-list-item-title">Mobile App</span>
                            </a>          
                                <span class="footer-list-item-sub">Shop &amp; get exclusive deals right from your phone.</span>
                        </li>
                        <li class="footer-list-item qa-footer-item-blog">
                            <div class="footer-list-item-title">
                                Blog:
                                <a class="divider footer-blog link-aeo-blog" href="http://blog.ae.com/?navdetail=footer:c1:p8" target="_blank" rel="noopener noreferrer">
                                    AEO
                                </a>
                                |
                                <a class="footer-blog link-aerie-blog" href="https://www.ae.com/aerie-real-life" target="_blank" rel="noopener noreferrer">
                                    Aerie
                                </a>
                            </div>
                            <span class="footer-list-item-sub">Style tips, DIY ideas &amp; more.</span>
                        </li>
                        <li class="footer-list-item qa-footer-item-ae-style-drop">
                            <a href="https://www.aestyledrop.com" rel="noopener noreferrer" target="_blank">
                                <span class="footer-list-item-title">AE Style Drop</span>
                            </a>
                            <span class="footer-list-item-sub">Rent, return and repeat.</span>
                        </li>
                    </ul>
                </div>
                <div class="footer-column">
                    <ul class="list-unstyled qa-footer-list-center-column footer-heritage-list">
                        <li class="footer-list-item qa-footer-item-store-locator">
                            <a href="//storelocations.ae.com/search.html?navdetail=footer:c2:p1">
                                <span class="footer-list-item-title">Store Locator</span>
                            </a>
                        </li>
                        <li class="footer-list-item qa-footer-item-track-order">
                            <a href="/us/en/trackorder?navdetail=footer%3Ac2%3Ap2" id="ember1062" class="ember-view">
                                <span class="footer-list-item-title">Track Order</span>
                            </a>        
                        </li>
                        <li class="footer-list-item qa-footer-item-email-signup">
                            <a tabindex="0" id="ember1063" class="clickable modal-email-signup qa-show-modal-email-signup ember-view">            
                                <span class="footer-list-item-title">Sign Up For Email</span>
                            </a>        
                        </li>
                        <li class="footer-list-item qa-footer-item-mobile-alerts">
                            <a tabindex="0" id="ember1064" class="clickable modal-mobile-signup qa-show-modal-mobile-signup ember-view">              
                                <span class="footer-list-item-title">Sign Up for Texts</span>
                            </a>         
                        </li>
                        <li class="footer-list-item qa-footer-item-shoprunner">
                            <a href="javascript:sr_$.learn('Header');">
                            <span class="footer-list-item-title">Shoprunner: Free 2-Day Shipping</span>
                            </a>
                        </li>
                    </ul>
                    <ul class="about-list list-unstyled">
                        <li class="extra-item">
                            <a class="footer-extra-item footer-link-about-aeo" href="https://www.aeo-inc.com/?navdetail=footer:c2:p6" target="_blank" rel="noopener">About AEO </a>
                        </li>
                        <li class="extra-item">
                            <a class="footer-extra-item footer-link-investors" href="http://investors.ae.com/overview/default.aspx?navdetail=footer:c2:p7" target="_blank" rel="noopener">Investors</a>
                        </li>
                        <li class="extra-item">
                            <a class="footer-extra-item footer-link-aeo-careers" href="http://www.liveyourlifeloveyourjob.com/?navdetail=footer:c2:p8" target="_blank" rel="noopener">Careers</a>
                        </li>
                        <li class="extra-item">
                            <a target="_self" href="/us/en/sitemap" id="ember1069" class="footer-extra-item footer-link-site-map ember-view">Site Map</a>          
                        </li>
                    </ul>
                </div>
                <div class="footer-column">
                    <h4 class="footer-item-title footer-question-title">Have a Question?</h4>
                    <ul class="dt-footer-help-list list-unstyled qa-footer-list-help-links">
                        <li class="extra-item qa-footer-link-call-us">
                            <a href="/us/en/content/help/call-us?navdetail=footer%3Ac3%3Ap1" id="ember1070" class="ember-view">Call Us: 1 (888) 232-4535</a>        
                        </li>
                        <li class="extra-item qa-footer-link-aeo-help">
                            <a href="/us/en/content/help/home?navdetail=footer%3Ac3p2" id="ember1071" class="ember-view">Help</a>        
                        </li>
                        <li class="extra-item qa-footer-link-return-policy">
                            <a href="/us/en/content/help/return-policy?navdetail=footer%3Ac3%3Ap3&amp;topic=1" id="ember1072" class="ember-view">Return Policy</a>        
                        </li>
                        <li class="extra-item qa-footer-link-email-us">
                            <a href="/us/en/contact?navdetail=footer%3Ac3%3Ap4" id="ember1073" class="footer-link-email-us ember-view">Email Us</a>  
                        </li>
                        <li class="extra-item qa-footer-link-aeo-feedback">
                            <span id="ember1074" class="clickable feedback __a6900 ember-view"><!---->  
                                <div id="awo_qualtrics_2" class="clickable feedback-button qa-feedback-button" data-awo="awo_qualtrics"></div>
                            </span>        
                        </li>
                    </ul>
                    <div class="footer-flag-currency">
                        <button tabindex="0" id="ember1076" class="i18n-icon btn-link clickable qa-i18n-icon __d75dc ember-view footer-item-title"> 
                            <span class="i18n-status-flag">
                                <img src="https://s7d2.scene7.com/is/image/aeo/flag__US?fit=crop&amp;wid=40&amp;qlt=90,0&amp;fmt=png-alpha" id="ember1077" class="country-flag ember-view">
                            </span>
                            <span class="i18n-icon-currency">$USD</span>
                        </button>
                    </div>
                    <div class="footer-follow">
                        <h4 class="footer-follow-title">Follow Us</h4>
                        <ul class="mb-footer-social-list social">
                            <li class="mb-footer-social-list-item">
                                <a class="qa-social-facebook" href="https://www.facebook.com/americaneagle" target="_blank" aria-label="Facebook link" rel="noopener noreferrer">
                                    <span id="ember239" class="fa fa-facebook image-fa"></span>
                                </a>
                            </li>
                            <li class="mb-footer-social-list-item">
                                <a class="qa-social-twitter" href="https://twitter.com/aeo" target="_blank" aria-label="Twitter link" rel="noopener noreferrer">
                                    <span id="ember240" class="fa fa-twitter image-fa"></span>
                                </a>
                            </li>
                            <li class="mb-footer-social-list-item">
                                <a class="qa-social-instagram" href="https://instagram.com/americaneagle" target="_blank" aria-label="Instagram link" rel="noopener noreferrer">
                                    <span id="ember241" class="fa fa-instagram image-fa"></span>
                                </a>
                            </li>
                            <li class="mb-footer-social-list-item">
                                <a class="qa-social-pinterest" href="https://www.pinterest.com/americaneagle" target="_blank" aria-label="Pinterest link" rel="noopener noreferrer">
                                    <span id="ember242" class="fa fa-pinterest-p image-fa"></span>
                                </a>
                            </li>
                            <li class="mb-footer-social-list-item">
                                <a class="social-youtube qa-social-youtube" href="https://www.youtube.com/user/americaneagle" target="_blank" aria-label="YouTube link" rel="noopener noreferrer">
                                    <span id="ember243" class="fa fa-youtube-square image-fa"></span>
                                </a>
                            </li>
                        </ul>
                        <ul class="list-inline hashtags">
                            <li>
                                <a href="/us/en/stylegallery" id="ember1088" class="qa-aeo-style ember-view">#AExME</a>            
                            </li>
                            <li>
                                <a href="/us/en/aerie/stylegallery" id="ember1089" class="qa-aerie-real ember-view">#AerieREAL</a>           
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-wapper-menu-dropdown-mobile">
                <!-- Mobile -->
                <div class="mb-footer-group panel panel-default col-xs-12">
                    <h4 class="panel-heading panel-title">
                            <a href="/us/en/x/gift-cards" id="ember217" class="mb-footer-heading mb-footer-gift-cards footer-item-gift-cards collapsed ember-view">Gift card</a>        
                    </h4>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12">
                    <h4 class="panel-heading panel-title">
                        <a href="/us/en/myaccount/aeoconnected" id="ember218" class="mb-footer-heading mb-footer-aeo-rewards footer-item-rewards collapsed ember-view">AEO Connected Rewards</a>        
                    </h4>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12 dropdown">
                    <h4 class="panel-heading panel-title dropdown-heading ">
                        <a data-toggle="collapse"class="mb-footer-heading mb-footer-credit-cards collapsed dropdown-title" data-parent="#accordion" href="#collapse_cc" aria-controls="collapse_cc" aria-expanded="false" aria-selected="false" tabindex="0">
                            AEO Connected Credit Cards
                            <span class="toggle-icon-header toggle-icon">
                                <span id="ember219" class="fa fa-plus"></span>
                            </span>
                        </a>
                    </h4>
                    <ul id="collapse_cc" class="panel-collapse list-unstyled text-capitalize collapse list-dropdown-aeo" aria-expanded="false" style="height: 0px;" aria-hidden="true" tabindex="-1">
                        <li class="mb-footer-group-item">
                            <a rel="noopener noreferrer" target="_blank" href="https://aeoutfitters.syf.com/eSecurity/Login/login.action?clientId=aeoutfitters&amp;accountType=generic&amp;langId=en" id="ember220" class="footer-link-pay-bill aecc-sign-in-link qa-aecc-sign-in-link ember-view">Pay Bill</a>          
                        </li>
                        <li class="mb-footer-group-item">
                            <a target="_blank" href="https://apply.syf.com/eapply/eapply.action?clientCode=AE&amp;cHash=1342177401&amp;subActionId=1000&amp;sitecode=" id="ember221" class="footer-link-apply-now aecc-sign-up-link qa-aecc-sign-up-link ember-view">Apply Now</a>
                        </li>
                        <li class="mb-footer-group-item">
                            <a href="/us/en/content/credit" id="ember222" class="footer-link-aeo-credit-cards ember-view">Card Benefits</a>          
                        </li>
                    </ul>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12">
                    <h4 class="panel-heading panel-title">
                        <a class="mb-footer-heading mb-footer-store-locator" href="//storelocations.ae.com/search.html">Store Locator</a>
                    </h4>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12">
                    <h4 class="panel-heading panel-title">
                        <a href="/us/en/trackorder" id="ember223" class="mb-footer-heading mb-footer-track-order ember-view">Track Order</a>      
                    </h4>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12">
                    <h4 class="panel-heading panel-title">
                        <a href="https://www.aestyledrop.com" class="mb-footer-heading mb-footer-ae-style-drop collapsed" rel="noopener noreferrer">
                            AE Style Drop
                        </a>
                    </h4>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12 dropdown">
                    <h4 class="panel-heading panel-title dropdown-heading">
                        <a data-toggle="collapse" class="mb-footer-heading mb-footer-stay-in-know collapsed dropdown-title" data-parent="#accordion" href="#collapseOne" aria-controls="collapseOne" aria-expanded="false">
                            Stay In The Know
                            <span class="toggle-icon-header toggle-icon">
                                <span id="ember224" class="fa fa-plus"></span>
                            </span>
                        </a>
                    </h4>
                    <ul id="collapseOne" class="panel-collapse collapse list-unstyled list-stay-in-the-down" aria-expanded="false">
                        <li class="mb-footer-group-item footer-item-email-signup">
                            <a tabindex="0" id="ember225" class="footer-link-email-signup clickable modal-email-signup qa-show-modal-email-signup ember-view">Sign Up For Email</a>       
                        </li>
                        <li class="mb-footer-group-item footer-item-app-download">
                            <a href="/us/en/x/mobile-app" class="xm-link-to qa-xm-link-to ">Mobile App</a>        
                        </li>
                        <li class="mb-footer-group-item footer-item-mobile-alerts">
                            <a tabindex="0" id="ember227" class="footer-link-mobile-alerts clickable modal-mobile-signup qa-show-modal-mobile-signup ember-view">Sign Up for Texts</a>          
                        </li>
                    </ul>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12 dropdown">
                    <h4 class="panel-heading panel-title dropdown-heading">
                        <a data-toggle="collapse" class="mb-footer-heading mb-footer-about-aeo collapsed dropdown-title" data-parent="#accordion" href="#collapseTwo" aria-controls="collapseTwo" aria-expanded="false" aria-selected="false" tabindex="0">About Us
                            <span class="toggle-icon-header toggle-icon">
                                <span id="ember228" class="fa fa-plus"></span>
                            </span>
                        </a>
                    </h4>
                    <ul id="collapseTwo" class="panel-collapse list-unstyled text-capitalize collapse list-about-us" aria-expanded="false" style="height: 0px;" aria-hidden="true" tabindex="-1">
                        <li class="mb-footer-group-item">
                            <a class="footer-link-about-aeo" href="https://www.aeo-inc.com/?navdetail=footer:c2:p6" target="_blank" rel="noopener">
                                About AEO
                            </a>
                        </li>
                        <li class="mb-footer-group-item">
                            <a class="footer-link-investors" href="http://investors.ae.com/overview/default.aspx?navdetail=footer:c2:p7" target="_blank" rel="noopener">
                                Investors
                            </a>
                        </li>
                        <li class="mb-footer-group-item">
                            <a class="footer-link-aeo-careers" href="http://www.liveyourlifeloveyourjob.com/?navdetail=footer:c2:p8" target="_blank" rel="noopener">
                                Careers
                            </a>
                        </li>
                        <li class="mb-footer-group-item">
                            <a target="_self" href="/us/en/sitemap" id="ember229" class="footer-link-site-map ember-view">                
                                Site Map
                            </a>          
                        </li>
                    </ul>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12 dropdown">
                    <h4 class="panel-heading panel-title dropdown-heading">
                        <a data-toggle="collapse" class="mb-footer-heading mb-footer-have-question collapsed dropdown-title" data-parent="#accordion" href="#collapseThree" aria-controls="collapseThree" aria-expanded="false">
                            Have a Question?
                            <span class="toggle-icon-header toggle-icon">
                                <span id="ember230" class="fa fa-plus"></span>
                            </span>
                        </a>
                    </h4>
                    <ul id="collapseThree" class="panel-collapse collapse list-unstyled text-capitalize list-have-a-question" aria-expanded="false">
                        <li class="mb-footer-group-item">
                            <a href="tel:+18882324535" class="msg-link msg-external-link footer-link-call-us" target="_self" rel="">Call Us: 1 (888) 232-4535</a>
                        </li>
                        <li class="mb-footer-group-item">
                            <a href="/us/en/content/help/home" id="ember231" class="footer-link-aeo-help ember-view">Help</a>        
                        </li>
                        <li class="mb-footer-group-item">
                            <a href="/us/en/content/help/return-policy?topic=1" id="ember232" class="footer-link-return-policy ember-view"></a>    
                        </li>
                        <li class="mb-footer-group-item">
                            <a href="/us/en/contact?navdetail=footer%3Ac3%3Ap3" id="ember233" class="footer-link-email-us ember-view">Email Us</a>        
                        </li>
                    </ul>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12">
                    <h4 class="panel-heading panel-title">
                        <span id="ember234" class="mb-footer-heading mb-footer-feedback collapsed __a6900 ember-view"><!---->  
                            <div id="awo_qualtrics_3" class="clickable feedback-button qa-feedback-button" data-awo="awo_qualtrics">
                                <a class="QSILink SI_836NFhQWRcTM6nX_Link" href="javascript:void(0);">Feedback</a></div>
                        </span>        
                    </h4>
                </div>
                <div class="mb-footer-group panel panel-default col-xs-12 dropdown">
                    <h4 class="panel-heading panel-title dropdown-heading">
                        <a data-toggle="collapse" data-parent="#accordion" class="mb-footer-heading mb-footer-privacy-policies collapsed dropdown-title" href="#collapseFour" aria-controls="collapseFour" aria-expanded="false">Privacy + Notices
                            <span class="toggle-icon-header toggle-icon">
                                <span id="ember236" class="fa fa-plus"></span>
                            </span>
                        </a>
                    </h4>
                    <ul aria-expanded="false" id="collapseFour" class="qa-list-policies-links panel-collapse collapse list-unstyled __7cae8 ember-view list-privacy-notice">  
                        <li class="mb-footer-group-item qa-footer-link-aeo-terms">
                            <a href="#" data-route="cms-page" data-path="help/terms-of-use" class="msg-link msg-link-cms-page-help/terms-of-use text-nowrap msg-link-to footer-link-aeo-terms" target="_blank" rel="nofollow">Terms of Use</a>
                        </li>
                        <li class="mb-footer-group-item qa-footer-link-california-compliance">
                            <a href="#" data-route="cms-page" data-path="help/california-disclosures" class="msg-link msg-link-cms-page-help/california-disclosures text-nowrap msg-link-to footer-link-california-compliance" target="" rel="nofollow">California Disclosures</a>
                        </li>
                        <li class="mb-footer-group-item qa-footer-link-privacy-policy">
                            <a href="#" data-route="cms-page" data-path="help/privacy-notice" class="msg-link msg-link-cms-page-help/privacy-notice text-nowrap msg-link-to footer-link-privacy-policy" target="_blank" rel="nofollow">Privacy Notices</a>
                        </li>
                        <li class="mb-footer-group-item qa-footer-link-brand-protection">
                            <a href="#" data-route="cms-page" data-path="help/brand-protection" class="msg-link msg-link-cms-page-help/brand-protection text-nowrap msg-link-to footer-link-brand-protection" target="" rel="nofollow">Brand Protection</a>
                        </li>
                        <li class="mb-footer-group-item qa-footer-link-affiliate-program">
                            <a href="https://signup.cj.com/member/signup/publisher.cj?cid=4445720" class="msg-link msg-external-link footer-link-affiliate-program" target="_blank" rel="noopener noreferrer">Affiliate Program</a>
                        </li>
                        <li class="mb-footer-group-item qa-footer-link-accessibility">
                            <a href="#" data-route="cms-page" data-path="help/accessibility" class="msg-link msg-link-cms-page-help/accessibility text-nowrap msg-link-to footer-link-accessibility" target="" rel="nofollow">Accessibility</a>
                        </li>
                    </ul>
                </div>
                <div class="mb-footer-group panel panel-default footer-flag-currency col-xs-12">
                    <h4 class="panel-heading panel-title">
                        <button tabindex="0" id="ember237" class="i18n-icon btn-link clickable qa-i18n-icon __d75dc ember-view mb-footer-heading">  
                            <span class="i18n-status-flag">
                                <img src="https://s7d2.scene7.com/is/image/aeo/flag__US?fit=crop&amp;wid=40&amp;qlt=80,0&amp;fmt=png-alpha" id="ember238" class="country-flag ember-view">
                            </span>
                            <span class="i18n-icon-currency">$USD</span>
                        </button>
                    </h4>
                </div>
            </div>
        </div>
        <div class="mb-footer-social">
            <div class="mb-footer-social-wrap footer-wrapper">
                <ul class="mb-footer-social-list social">
                    <li class="mb-footer-social-list-item">
                        <a class="qa-social-facebook" href="https://www.facebook.com/americaneagle" target="_blank" aria-label="Facebook link" rel="noopener noreferrer">
                            <span id="ember239" class="fa fa-facebook image-fa"></span>
                        </a>
                    </li>
                    <li class="mb-footer-social-list-item">
                        <a class="qa-social-twitter" href="https://twitter.com/aeo" target="_blank" aria-label="Twitter link" rel="noopener noreferrer">
                            <span id="ember240" class="fa fa-twitter image-fa"></span>
                        </a>
                    </li>
                    <li class="mb-footer-social-list-item">
                        <a class="qa-social-instagram" href="https://instagram.com/americaneagle" target="_blank" aria-label="Instagram link" rel="noopener noreferrer">
                            <span id="ember241" class="fa fa-instagram image-fa"></span>
                        </a>
                    </li>
                    <li class="mb-footer-social-list-item">
                        <a class="qa-social-pinterest" href="https://www.pinterest.com/americaneagle" target="_blank" aria-label="Pinterest link" rel="noopener noreferrer">
                            <span id="ember242" class="fa fa-pinterest-p image-fa"></span>
                        </a>
                    </li>
                    <li class="mb-footer-social-list-item">
                        <a class="social-youtube qa-social-youtube" href="https://www.youtube.com/user/americaneagle" target="_blank" aria-label="YouTube link" rel="noopener noreferrer">
                            <span id="ember243" class="fa fa-youtube image-fa"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <ul class="mb-footer-hashtags-list list-inline footer-wrapper-blog">
                <li>
                    <a href="/us/en/stylegallery" id="ember244" class="ember-view">AExME</a>      
                </li>
                <li>
                    <a href="/us/en/aerie/stylegallery" id="ember245" class="ember-view">#AerieREAL</a>      
                </li>
            </ul>
            <div class="footer-wrapper-blog footer-blog mb-footer-blog-list">
                <span id="ember246" class="fa fa-rss image-fa"></span>
                Blog:
                <a class="divider footer-blog  footer-link-aeo-blog" href="http://blog.ae.com" target="_blank" rel="noopener noreferrer">AEO</a>
                |
                <a class="footer-blog footer-link-aerie-blog" href="https://www.ae.com/aerie-real-life" target="_blank" rel="noopener noreferrer"> Aerie</a>
            </div>
        </div>  
        
        <hr class="footer-separator visible-lg">
        <div class="footer-wrapper footer-wrapper-social-mobile">
            <ul id="ember1090" class="qa-list-policies-links list-inline list-policies-links __7cae8 ember-view">
                <li class="extra-item qa-footer-link-aeo-terms">
                    <a href="#" data-route="cms-page" data-path="help/terms-of-use" class="msg-link msg-link-cms-page-help/terms-of-use text-nowrap msg-link-to footer-link-aeo-terms" target="_blank" rel="nofollow">Terms of Use</a>
                </li>
                <li class="extra-item qa-footer-link-california-compliance">
                    <a href="#" data-route="cms-page" data-path="help/california-disclosures" class="msg-link msg-link-cms-page-help/california-disclosures text-nowrap msg-link-to footer-link-california-compliance" target="" rel="nofollow">California Disclosures</a>
                </li>
                <li class="extra-item qa-footer-link-privacy-policy">
                    <a href="#" data-route="cms-page" data-path="help/privacy-notice" class="msg-link msg-link-cms-page-help/privacy-notice text-nowrap msg-link-to footer-link-privacy-policy" target="_blank" rel="nofollow">Privacy Notices</a>
                </li>
                <li class="extra-item qa-footer-link-brand-protection">
                    <a href="#" data-route="cms-page" data-path="help/brand-protection" class="msg-link msg-link-cms-page-help/brand-protection text-nowrap msg-link-to footer-link-brand-protection" target="" rel="nofollow">Brand Protection</a>
                </li>
                <li class="extra-item qa-footer-link-affiliate-program">
                    <a href="https://signup.cj.com/member/signup/publisher.cj?cid=4445720" class="msg-link msg-external-link footer-link-affiliate-program" target="_blank" rel="noopener noreferrer">Affiliate Program</a>
                </li>
                <li class="extra-item qa-footer-link-accessibility">
                    <a href="#" data-route="cms-page" data-path="help/accessibility" class="msg-link msg-link-cms-page-help/accessibility text-nowrap msg-link-to footer-link-accessibility" target="" rel="nofollow">Accessibility</a>
                </li>
            </ul>
        </div>
        <div class="footer-wrapper-bottom">
            <p id="ember1130" class="copyright __31026 ember-view">© 2019 AEO Management Co. All Rights Reserved</p>
            <div class="footer-logos">
                <img class="footer-copyright-image"src="<?php echo $this->getViewFileUrl("images/image_footer.png"); ?>">
            </div>
        </div>
    </div>
<?php elseif($footer == 'footer_2'): ?>
    <div class="footer-container">
        <div class="top-footer">
            <div class="container">
                <!-- Static block: footer_block_newsletter_top -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_newsletter_top')->setCanUsePanel($canUsePanel)->toHtml() ?>
            </div>
        </div>
        <div class="middle-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_contact_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
						<?php echo $this->getLayout()->createBlock('Magento\Store\Block\Switcher')->setTemplate('switch/stores.phtml')->toHtml() ?>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_categories -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="clearfix visible-sm"></div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="clearfix visible-sm"></div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_instagram -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_instagram')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-7 col-sm-12 col-xs-12 copyright">
                        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                    </div>
                    <div class="col-lg-6 col-md-5 col-sm-12 col-xs-12">
                        <!-- Static block: footer_block_menu_bottom -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_menu_bottom')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php elseif($footer == 'footer_3'): ?>
    <div class="footer-container">
        <div class="bottom-footer">
            <div class="container">
                <!-- Static block: footer_logo_and_social -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_logo_and_social')->setCanUsePanel($canUsePanel)->toHtml() ?>
				
                <!-- Static block: claue_footer3_custom_menu -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('claue_footer3_custom_menu')->setCanUsePanel($canUsePanel)->toHtml() ?>
				
				<?php echo $this->getLayout()->createBlock('Magento\Store\Block\Switcher')->setTemplate('switch/stores.phtml')->toHtml() ?>
                <div class="copyright">
                    <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                </div>
            </div>
        </div>
    </div>
<?php elseif($footer == 'footer_4'): ?>
    <div class="footer-container">
        <div class="top-footer">
            <div class="container">
                <!-- Static block: footer_block_newsletter_top -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_newsletter_top')->setCanUsePanel($canUsePanel)->toHtml() ?>
				
            </div>
        </div>
        <?php
            // Background Image Left Footer
            $backgroundImage = "";
            $staticImage =  $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_background_image')->toHtml();
            if($staticImage != null) {
                preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $staticImage, $matches);
                if(!empty($matches[1][0])){
                    $backgroundImage = $matches[1][0];
                }
            }
        ?>
        <div class="middle-footer-container">
            <div class="middle-col" <?php if($backgroundImage != ""): ?>style="background-image:url(<?php echo $backgroundImage ?>);"<?php endif ?>>
                <div class="visible-builder text-center">
                    <a class="btn btn-default btn-xs" href="javascript:void(0)" data-toggle="modal" data-target="#change_bg_footer">Change Background</a>
                    <div id="change_bg_footer" class="modal fade" style="display: none;" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"><button class="close" type="button" data-dismiss="modal">x</button>
                                <div class="modal-body">
                                    To change background-image of this col, you can create a static block with identifier footer_background_image. Insert an image to content of this static block.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="middle-footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 margin-bottom40">
                                <!-- Static block: footer4_contact_us -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer4_contact_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
								
								
                            </div>
                            <div class="col-lg-4 col-sm-4 col-xs-12 margin-bottom40">
                                <!-- Static block: footer_block_categories -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
								<?php echo $this->getLayout()->createBlock('Magento\Store\Block\Switcher')->setTemplate('switch/stores.phtml')->toHtml() ?>
                            </div>
                            <div class="col-lg-4 col-sm-4 col-xs-12 margin-bottom40">
                                <!-- Static block: footer_block_infomation -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->setCanUsePanel($canUsePanel)->toHtml() ?>
                            </div>
                            <div class="col-lg-4 col-sm-4 col-xs-12 margin-bottom40">
                                <!-- Static block: footer_block_quick_link -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->setCanUsePanel($canUsePanel)->toHtml() ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bottom-footer">
                    <div class="container">
                        <div class="copyright">
                            <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                        </div>
                    </div>
                </div>
            </div>
            <div id="footer-map" class="footer-map">
                <!-- Static block: footer_block_image_map -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_image_map')->setCanUsePanel($canUsePanel)->toHtml() ?>
            </div>
        </div>
    </div>
<?php endif ?>