<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

use Wiki\VendorsProfile\Block\Profile;

/** @var  Profile $block */

$defaultImage = $this->getViewFileUrl('Wiki_VendorsProfile::images/default.jpg');
$defaultLogo = $this->getViewFileUrl('Wiki_VendorsProfile::images/default_logo.png');
?>
<div id="profile_edit_info" data-bind="scope: 'profile'">
    <div class="bg-profile">

        <!-- ko if:(getPendingBackground().size()) -->
        <img data-bind="attr: {'src': backgroundImg}" alt="background" class="w-100">
        <!-- /ko -->

        <!-- ko ifnot:(getPendingBackground().size()) -->
        <img src="<?= $block->getBackgroundImage() ?: $defaultImage ?>" alt="background" class="w-100">
        <!-- /ko -->

        <div class="p-form-image-upload w-100">
            <input type="file" id="profile-image" name="profile-image" accept="image/*" class="hidden"
                   data-bind="event: {change: onElementRender}" multiple>
            <label for="profile-image" class="p-form-image-upload__label px-3 h4"><?= __('upload image') ?></label>
        </div>

    </div>
    <div class="container-md">
        <div class="flex flex-nowrap">
            <div class="profile-logo">

                <!-- ko if: (getPendingAvatar().size()) -->
                <img data-bind="attr: {'src': avatarImg}" alt="default_logo">
                <!-- /ko -->

                <!-- ko ifnot: (getPendingAvatar().size()) -->
                <img src="<?= $block->getSellerImage() ?: $defaultLogo ?>" alt="default_logo">
                <!-- /ko -->

                <div class="p-form-logo-upload w-100">
                    <input type="file" id="profile-logo" name="profile-logo" class="hidden" accept="image/*"
                           data-bind="event: {change: onElementRender}"/>
                    <label for="profile-logo" class="p-form-logo-upload__label"><?= __('upload avatar') ?></label>
                </div>
            </div>

            <div class="pt-3 pl-2 w-100">
                <div class="a-form flex flex-nowrap va-center">
                    <h4 class="a-form--required a-form--nowrap py-2 pr-4"><?= __('Name') ?></h4>
                    <div class="a-form-input w-100">
                        <input type="text" id="shop-name" value="<?= $block->getSellerName() ?>"
                               placeholder="Shop Name" data-reset="<?= $block->getSellerName() ?>">
                    </div>
                </div>
            </div>
        </div>
        <div class="p-seller-profile__inner">
            <div class="a-form mb-4">
                <h4 class="py-2 pr-4"><?= __('shop details') ?></h4>
                <div class="a-form-input">
                    <textarea placeholder="Write something briefly about the shop" id="shop-description"
                              data-reset="<?= $block->getSellerDes() ?>"><?= $block->getSellerDes() ?></textarea>
                </div>
            </div>
            <div class="a-form mb-5">
                <h4 class="py-2 pr-4"><?= __('Edit Banner') ?></h4>

                <div class="py-4">
                    <div class="a-form"
                         data-bind="foreach: {data: getPendingBanner()}">
                        <img data-bind="attr: {'src': $data.image}" alt="image">
                    </div>
                </div>

                <button class="variant-blue a-btn flex-nowidth" data-bind="click: bannerModalToggle">
                    <i class="a-icon a-btn__icon material-icons">add</i>
                    <span class="a-btn__text"
                          data-bind="i18n: 'add image or video (' + getPendingBanner().size() + '/6)'"></span>
                </button>
            </div>
            <div class="flex flex-cols-3 va-center ha-center g-3">
                <div>
                    <button class="variant-white w-100 a-btn" data-bind="click: clear">
                        <span class="a-btn__text"><?= __('clear') ?></span>
                    </button>
                </div>
                <div>
                    <button class="variant-yellow mx-auto w-100 a-btn">
                        <span class="a-btn__text"><?= __('correct') ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="image-modal" id="image-modal">
        <div class="image-container">
            <div class="image-modal__meta flex">
                <div class="image-modal__back flex ha-space-between">
                    <button class="a-btn a-btn--no-border" data-bind="click: bannerModalToggle">
                        <i class="a-icon a-btn__icon material-icons">chevron_left</i>
                    </button>
                </div>
                <h2 class="image-modal__title"><?= __('edit banner') ?></h2>
            </div>
            <div id="msg-error"></div>
            <div class="image-modal__content">
                <div class="container-default">
                    <div class="a-form-upload-banner">
                        <input type="file" multiple="multiple" id="profile-banners" name="profile-banners"
                               accept="image/*" class="hidden" data-bind="event: {change: onElementRender}">
                        <div>
                            <div class="a-form-upload-banner__images">
                                <!-- ko if: (getPendingBanner().size()) -->
                                <div class="a-form-upload-banner__images" data-bind="foreach: getPendingBanner()">
                                    <div class="mb-4 a-form-upload-banner__thumbnail p-2">
                                        <img data-bind="attr: {'src': $data.image}" alt="image">
                                        <p class="a-form-upload-banner__name" data-bind="text: $data.name"></p>
                                        <span class="a-form-upload-banner__close"
                                              data-bind="click: function(data, event) {return $parent.removeBanner(data, event)}">
                                                <i class="a-icon material-icons">close</i>
                                            </span>
                                    </div>
                                </div>
                                <!--/ko-->
                            </div>
                            <div>
                                <!-- ko if: (getPendingBanner().size() < 6) -->
                                <label for="profile-banners" class="a-form-upload-banner__label text-center">
                                    <i class="a-icon a-icon--medium material-icons">add</i>
                                    <span><?= __('add') ?></span>
                                </label>
                                <!-- /ko -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#profile_edit_info": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
    echo $block->getJsLayout(); ?>
        }
    }

</script>

