<?php 

// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $customerSession = $objectManager->get('Magento\Customer\Model\Session');

$objectManager =  '\Magento\Framework\App\ObjectManager'::getInstance();
$context = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
if($isLoggedIn) {
 

$blockObj= $block->getLayout()->createBlock('Wiki\VendorsNotification\Block\Frontend\Display');
$blockObj->flushCache();
// $fetchNoti = $blockObj->test();

$notificationCount = $block->getNotifiationCount();





?> 
<li class="dropdown notifications-menu">
    <a href="#" class="dropdown-toggle">
      <i class="fa fa-bell-o"></i>
      <?php if($notificationCount):?> <span id="notification-count" class="label label-warning"><?php echo $notificationCount?></span><?php endif;?>
        <span><?php echo __("Notification")?></span>
    </a>
    <ul class="dropdown-menu notifications-dropdown-menu">
        <li class="header">
            <!-- You have %1 unread notifications  -->
            <strong><?php echo __("Notifications")?></strong>
            <a class="mark-as-read pull-right" href="#"><?php echo __("Mark all as read")?></a>
        </li> 
        <?php if(!$block->getNotificationCollection()->count()):?>
            <li class="header"><?php echo __("You have no notification");?></li>
        <?php endif;?>
        <li>
        <ul class="menu">
                 <?php foreach($block->getNotificationCollection() as $notification){

                      $notificationType = $notification->getNotificationType();
                      
                      if($notification->getData('noti_admin_id') == 0){

                      
                      
                      ?>
                <li <?php if($notification->getData('is_read') == 0):?> class="unread"<?php endif;?>>
                
                    <a data-toggle="tooltip" title="<?php echo strip_tags($notificationType->getMessage())?>" href="<?php echo $blockObj->getURLOder($notificationType->getMessage());?>"><i class="<?php echo $notificationType->getIconClass()?>"></i> <?php echo $notificationType->getMessage()?></a>
                </li>
                <?php } else {   $listAdmin = $blockObj->getNotiAdmin($notification->getData('noti_admin_id'));
                    ?>
                    <li <?php if($notification->getData('is_read') == 0):?> class="unread"<?php endif;?>>
                
                        <a data-toggle="tooltip" title="<?php echo strip_tags($notificationType->getMessage())?>" href="<?php echo $blockObj->getURLDetailNoti().$notification->getData('noti_admin_id') ;?>"><i class="<?php echo $notificationType->getIconClass()?>"></i> 
                        <?php echo $listAdmin['title'];?></a>
                    </li>
               <?php  }
                 }
                ?> 
            </ul>
          </li>
        <li class="footer"><a href="<?php echo $block->getViewAllUrl()?>"><?php echo __("View all")?></a></li>
    </ul>
</li>

<?php } ?>


<script type="text/javascript">
var URL_MARK_AS_READ = '<?php echo $block->getBaseUrl().'usernoti/index/MarkAllRead';?>';
require([
         'jquery',
         'domReady!'
     ], function($){
    jQuery(".notifications-menu a.dropdown-toggle").click(function(){
        $(this).parent().toggleClass('open');
    });

    $('body').click(function(event){
        var elms = [
            '.dropdown-menu .header',
            '.dropdown-menu .header strong',
            '.notifications-menu .dropdown-toggle',
            '.notifications-menu .dropdown-toggle i',
            '.notifications-menu .dropdown-toggle span',
            '.notifications-menu .mark-as-read'
        ];
    	if (!event.target.matches(elms.join())) {
        	$('.notifications-menu').removeClass('open');
    	}
    });

    $('.notifications-menu .mark-as-read').click(function(){
    	$.ajax({
  		  url: URL_MARK_AS_READ,
  		  method: "POST",
  		  dataType: "json"
		}).done(function( response ){
           
	  	  	if(response.ajaxExpired){
	  	  	  	window.location = response.ajaxRedirect;
	  	  	  	return;
	  	  	}
	  	  	if(response.success){
		  	  	$('.notifications-menu .unread').removeClass('unread');
		  	  	$('#notification-count').hide();
	  	  	}	  	  	
		});
    });
});
</script>